filter:
    excluded_paths:
        - 'vendor/*'
build:
    dependencies:
        override:
            - 'composer install --no-interaction'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: clover.xml
                    format: php-clover
tools:
    php_mess_detector:
        filter:
            excluded_paths: ['vendor/*']
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            excluded_paths: ['vendor/*']
    php_code_coverage:
        test_command: vendor/bin/phpunit
        filter:
            excluded_paths: ['vendor/*']
    php_cpd: false
    php_pdepend:
        excluded_dirs:
            1: vendor
    php_loc:
        excluded_dirs:
            - vendor