language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

sudo: false

before_script:
  - composer update --dev --no-interaction --prefer-source $PREFER_LOWEST

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist
